name: $(Date:yyyyMMdd)$(Rev:.r)_e2e

pool:
  vmImage: ubuntu-18.04

jobs:
- job: E2E
  steps:
  - bash: |
      cd e2e
      bash ./testscript.sh
    displayName: harshatest     
  - bash: |
      cd e2e
      bash ./e2e-script.sh
    displayName: run e2e   
  - publish: $(System.DefaultWorkingDirectory)/e2e/logs
    artifact: logs
